### PR TITLE
fix usage of jid.user

### PR DESCRIPTION
**Pull request by sonnyp**
jid.user was deprecated for a long time and is now removed from node-xmpp-jid

### CODE REVIEW

**Comment by lloydwatkin** [comment]
Hmm it might be used by people using the library since its reported back by node-xmpp-client on connection

**Comment by sonnyp** [comment]
@lloydwatkin I don't follow what you are referring to.

It was released (for every module) as major version change.
But yeah maybe it was a bit rushed as you wouldn't get any error; just undefined.

Do you think we should put user back?

**Comment by lloydwatkin** [comment]
I think so, but with a deprecation notice in the readme?

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/JID/pull/5

**Pull request merged**
