### PR TITLE
WebSocket RFC

### PR DESCRIPTION
**Pull request by sonnyp**
WIP

### CODE REVIEW

**Comment by lloydwatkin** [comment]
:+1:

**Comment by sonnyp** [comment]
https://github.com/node-xmpp/node-xmpp-client/pull/147 is required first

**Comment by sonnyp** [comment]
for some reason websocket module was removed from community modules repository and is now only available in prosody 0.10

**Comment by lloydwatkin** [comment]
Go for it, XMPP won't have changed, and once we have the latest websocket support from Prosody 0.10 and `node-xmpp-client` I can put integration tests in place.

**Comment by sonnyp** [comment]
okay, prosody updated to 0.10 but BOSH and TCP tests are failing, dunno why

**Comment by lloydwatkin** [comment]
Create a branch with an environment variable of `DEBUG` equal to `*` this will tell you what is going on client side, that might help. If not then you can install prosody 0.10 locally with the same config and see what's happening in the prosody logs.

**Comment by sonnyp** [comment]
@lloydwatkin if you have the opportunity to have a look that'd be great

**Comment by sonnyp** [comment]
fixed in https://github.com/node-xmpp/node-xmpp-client/pull/154 
WebSocket tests run against node-xmpp-server until we update prosody

**Pull request closed without merging**
