### PR TITLE
move wait to bosh opt

### PR DESCRIPTION
**Pull request by sonnyp**
options.bosh.wait instead of options.wait

@lloydwatkin any idea why the default is 10 seconds? seems rather low, I believe 60 is the 'standard'

### CODE REVIEW

**Comment by chris-rock** [comment]
+1

**Comment by lloydwatkin** [comment]
Happy to merge. Can we make sure the manual is updated too?

**Comment by sonnyp** [comment]
yes, on it!

**Comment by sonnyp** [comment]
done http://node-xmpp.org/doc/client.html

**Pull request merged**
