### PR TITLE
Fix BOSH for ejabberd

### PR DESCRIPTION
**Pull request by mweibel**
I had to make a quick fix to make BOSH work for ejabberd. The main issue was that the xmpp:restart was not correctly sent and also that the contentType was malformed. 
It's not really a good change (especially this initialStart thingy) but it might help as a start for fixing the BOSH connection type.

### CODE REVIEW

**Comment by sonnyp** [comment]
@mweibel thanks! when is ```startStream``` supposed to be called?

**Comment by mweibel** [comment]
It's called when the connection is connected:
https://github.com/node-xmpp/node-xmpp-client/blob/c0a756b8f8fb548160b890240375cebfb44a21b6/lib/session.js#L129

**Comment by sonnyp** [comment]
@mweibel this is for WebSocket

**Comment by mweibel** [comment]
Ah, yeah I see, but:
https://github.com/node-xmpp/node-xmpp-client/blob/c0a756b8f8fb548160b890240375cebfb44a21b6/lib/session.js#L163
Which is called here: https://github.com/node-xmpp/node-xmpp-client/blob/c0a756b8f8fb548160b890240375cebfb44a21b6/lib/session.js#L118

So I think it's a bit weird to have a separate startStream call in the websocket setup when it's anyway also calling addConnectionListeners

**Comment by sonnyp** [comment]
@mweibel yes! I'll tackle this thanks.

Need a bit more work as restart stream isn't mandatory.

**Comment by sonnyp** [comment]
BTW I've sent a PR for the xmpp:version and correct content attribute.
https://github.com/node-xmpp/node-xmpp-client/pull/90

@mweibel I'll merge your PR into a branch and work on it if that's okay.

**Comment by mweibel** [comment]
Sure, do that :)

**Comment by sonnyp** [comment]
Here is the branch I'm working on 
https://github.com/node-xmpp/node-xmpp-client/tree/bosh-restart

**Comment by sonnyp** [comment]
Fixed.
PR is https://github.com/node-xmpp/node-xmpp-client/pull/91 and has been merged.

**Pull request closed without merging**
